### ISSUE TITLE
Kia e-Niro Node-red Charge control

### ISSUE THREAD

**Issue by jemarr** [SondreNjaastad/node-red-contrib-bluelinky#12]
Hi.
I've a Node-red server on Raspberry Pi controlling all my home. Last year I installed solar pannels, so now I can control water heater when I have enought solar energy.

My chalenge is to control the On/Off charge of my new e-Niro with Node-red, to start/stop charging when I have spare solar power.

Will be charging control available in your project ?

Thanks.

**Comment by SondreNjaastad** [comment]
Hi!

This project is a wrapper around Bluelinky (https://github.com/Hacksore/Bluelinky). If Bluelinky will ever support Kia cars, this project will as well. You should open an issue there 😊
