### ISSUE TITLE
Cannot configure start node to set climate control etc

### ISSUE THREAD

**Issue by dcnoren** [SondreNjaastad/node-red-contrib-bluelinky#18]
Start car does not offer any config parameters:
![image](https://user-images.githubusercontent.com/3228595/100236198-56088500-2efb-11eb-99df-ebbdc53bced4.png)

Also seems that I am unable to pass the config on to the node.

Would like to start the car with heat or A/C, etc.

**Comment by MehrCurry** [comment]
I tried to send a payload to the node with `{"airCtrl":"true","igniOnDuration":"1","airTempvalue":"21","defrost":"false","heating1":"yes"}` which i tought should start the heating but it does not seem to work and the node produces no output.

**Comment by justinoreilly** [comment]
Is there any movement on this issue? I seem to be experiencing the same behavior and would love to see payloads working.

**Comment by Hacksore** [comment]
I believe I was able to send a start command via the inject node containing a payload like this.
```json
{
  "airCtrl": false,
  "igniOnDuration": 1,
  "airTempvalue": 70,
  "defrost": false,
  "heating1": false
}
```

![image](https://user-images.githubusercontent.com/996134/102738256-2f2d4b00-430f-11eb-8593-7a90cc889095.png)
![image](https://user-images.githubusercontent.com/996134/102738266-38b6b300-430f-11eb-841e-bcd098356d52.png)

**Comment by guyaumetremblay** [comment]
Hi! 
I tried with this configuration for an EV but it doesn't work: 
```
{ 
    "defrost":true,
    "windscreenHeating":true,
    "temperature":21.5,
    "unit":"C"
}
```
![Capture d’écran, le 2020-12-26 à 12 18 54](https://user-images.githubusercontent.com/17008947/103156228-91090d00-4774-11eb-94a4-6f674521d1e9.png)
(tried with both inject and map node)

And the result payload is only undefined: 

![Capture d’écran, le 2020-12-26 à 12 19 39](https://user-images.githubusercontent.com/17008947/103156248-aa11be00-4774-11eb-8569-424b704763ea.png)

And nothing happened ...

**Comment by Hacksore** [comment]
@guyaumetremblay It was mentioned on [discord by Truffle89](https://discord.com/channels/652755205041029120/708071576372772917/793995730738085889) from EU that they used this and it worked. I mean it's very well possible that EV's use a different endpoint to start the climate.

```json
{
  "temperature": 20.5,
  "defrost": false,
  "windscreenHeating": false
}
```

**Comment by guyaumetremblay** [comment]
@Hacksore Ok so it's possible that in the CA region, the json input template is different

**Comment by guyaumetremblay** [comment]
@Hacksore As I can see, with Fiddler, the mybluelink.ca is using this format: 
```
{
  "hvacInfo": {
    "airCtrl": 1,
    "defrost": true,
    "airTemp": {
      "value": "0EH",
      "unit": 0,
      "hvacTempType": 1
    },
    "heating1": 1
  },
  "pin": "...."
}
```

API url : `https://mybluelink.ca/tods/api/evc/rfon`

Response: 
```
{
  "responseHeader": {
    "responseCode": 0,
    "responseDesc": "Success"
  }
}
```

**Comment by Hacksore** [comment]
I think for the sake of this we really need issues to start listing what region they are attempting as well as if they are attempting to start an EV.

I see in the latest release we have the CA versions that you mentioned @guyaumetremblay 
https://github.com/Hacksore/bluelinky/blob/4b446dd9d4eaf2c729ab9cecae5f6914c1d77b85/lib/vehicles/canadian.vehicle.ts#L166

**Comment by guyaumetremblay** [comment]
@Hacksore Thanks! This format work: 
```
{
  airCtrl: Boolean,
  heating1: Boolean,
  defrost: Boolean,
  airTempvalue: number | null
}
  ```
So this is the documentation for the node "start care" which is wrong for CA !
