### ISSUE TITLE
Write a proper README

### ISSUE THREAD

**Issue by SondreNjaastad** [SondreNjaastad/node-red-contrib-bluelinky#2]
We need a proper readme for this project. Current readme is basicly copied from Bluelinky itself. The readme should refrence bluelinky properly, and highlight that this project mostly is a wrapper for bluelinky,

**Comment by Hacksore** [comment]
I updated the readme in #13 but don't know if that's good enough to close this.

**Comment by SondreNjaastad** [comment]
Lets settle with the way it is now, and make further improvements as we go.
