### ISSUE TITLE
Improvment for Climate Control

### ISSUE THREAD

**Issue by xerion3800** [SondreNjaastad/node-red-contrib-bluelinky#24]
In the Bluelink App it is possible to use two diferent Climate Controls. Once with Schedule and the other one for directly climate.
When i use the directly Climate then is the duration time 15 minutes. When i use the Schedule then is the duration time is 30 minutes. In Bluelinky i can "only" use the 15 minutes Mode. Could it be possible to add the Schedule in Bluelinky that i can change the schedule via Smart Home for example? Or is an another possibility to use the 30 Minute Mode?

**Comment by Hacksore** [comment]
@xerion3800 This issue might be better housed in the bluelinky repo as it's a core feature request.
