### ISSUE TITLE
API Error - HTTPError: Response code 401 (Authorization Required)

### ISSUE THREAD

**Issue by jdfrey1** [SondreNjaastad/node-red-contrib-bluelinky#25]
Opening a new issue that seems similar to a prior problem but that was closed several months ago.  I am using Bluelinky v.0.0.15 within a Home Assistant Node-Red installation.  I have a small routine that uses the "car location" node.  I try to update it every hour and also when I arrive at home.  This works and the location gets updated when I initially Deploy the flow but at subsequent runs it fails with an API Error.  It fails as soon as the car location node is activated and gives the message:  "HTTPError: Response code 401 (Authorization Required)".  If I restart the flow again It will update properly.

I'm attaching a couple of pictures to show the error states and my debug window.  From the debug window you can see it was successful at 10:50 AM but when it ran again at 11:00 AM it failed.

Any help would be appreciated to help make this more reliable.

![Palisade location - error](https://user-images.githubusercontent.com/65366070/106924366-00abd980-66dd-11eb-87e0-2677deb0f9a7.JPG)
![Palisade location - error 2](https://user-images.githubusercontent.com/65366070/106924373-02759d00-66dd-11eb-8e3b-ad6996827d8a.JPG)

**Comment by Hacksore** [comment]
Please report back if latest version still has this issue.
