### ISSUE TITLE
Bluelinky now supports KIA - Brand field missing from setup

### ISSUE THREAD

**Issue by holdestmade** [SondreNjaastad/node-red-contrib-bluelinky#36]
Installed latest Bluelinky to replace KUVORK as that is now deprecated.

Bluelinky takes a Brand config (KIA or HYUNDAI) but this does not appear in this node-red-contrib

Would it be possible to add or am I missing something ?

**Comment by holdestmade** [comment]
Just noticed theres a PR already, sorry

**Comment by PierreLevres** [comment]
The PR is merged, so you can run again..

**Comment by holdestmade** [comment]
Thanks, I'm using NR in HA and it still says v0.0.17 is installed, so the setup dialog still hasn't got the Brand field, when will you do a new release ?

Thanks

**Comment by PierreLevres** [comment]
the job publish-NPM needs to run on git, I PR’d an update for package.json, which will trigger that hopefully. Hacksore needs to release it….

**Comment by holdestmade** [comment]
Thanks
