### ISSUE TITLE
No Config Node in 0.0.18

### ISSUE THREAD

**Issue by holdestmade** [SondreNjaastad/node-red-contrib-bluelinky#38]
When adding a node in NodeRed and double clicking to set the config, it  just shows _Name_ and _Config_ fields and the _Config_ field says _Bluelinky config_ and nowhere to enter any credentials

There is no Global Configuration Node created.

The config panel was there in 0.0.17, albeit without the Brand field

![123](https://user-images.githubusercontent.com/13977244/112992484-1e873f00-9160-11eb-894e-a12a8ecf7188.jpg)

+ bluelinky@7.0.1
+ node-red-contrib-bluelinky@0.0.18

**Comment by PierreLevres** [comment]
Dit you restart node-red after updating bluelinky to 0.0.18?
Do you have any errors in you palette settings? 

There should be a pencil next to the BlueLinky config, to edit credentials.
<img width="517" alt="Screenshot 2021-03-30 at 15 31 45" src="https://user-images.githubusercontent.com/62832923/112997436-695b8380-916d-11eb-85d8-d59b769aa194.png">
<img width="525" alt="Screenshot 2021-03-30 at 15 31 51" src="https://user-images.githubusercontent.com/62832923/112997468-6f516480-916d-11eb-9ca7-a0ea2d0599bf.png">

How many nodes do you have? If not too many, try to delete the configuration node, redeploy flows and create a new config node.

**Comment by holdestmade** [comment]
Hi, I've tried all those things, as well as deleting the config json files and still the same. 
The pencil icon is no there, see my screenshot above.
In discussions on Discord and HackSore is looking into it
