### ISSUE TITLE
Start Kia EV error

### ISSUE THREAD

**Issue by olivierjag2** [SondreNjaastad/node-red-contrib-bluelinky#47]
Hi,

With node-red, I created function with this data:

msg.payload =
{
    "airCtrl": true,
    "heating1": false,
    "defrost": false,
    "airTempvalue": 23
}

return msg;

My car start but I receive always error in my debug : 
msg.payload : string[23]
"Failed to start vehicle"

Do you have idea to receive start car message?

For information, when I lock, unlock or stop car I receive successful message

**Comment by Hacksore** [comment]
Would be best to know what region you are attempting this from @olivierjag2 

We've seen discrepancies with starting based on region and the inputs. This is something that eventually we should look to standardize in bliuelinky to make it more generic

**Comment by olivierjag2** [comment]
I leave in canada

**Comment by Hacksore** [comment]
@olivierjag2 does this work for you?

https://github.com/SondreNjaastad/node-red-contrib-bluelinky/issues/18#issuecomment-754851538

**Comment by olivierjag2** [comment]
Yes work fine but i receive the error in node red

**Comment by guyaumetremblay** [comment]
@Hacksore @olivierjag2 I think this is the bug which has been fixed in this PR : https://github.com/Hacksore/bluelinky/pull/128
Probably just need an update of the Bluelinky version used in this node red plugin?

**Comment by olivierjag2** [comment]
yes! Works with the new version!

weird problem, if I put 22 for temperature my car does't start but 23 yes...

**Comment by guyaumetremblay** [comment]
@olivierjag2 Probably link to https://github.com/Hacksore/bluelinky/issues/96

**Comment by olivierjag2** [comment]
> @olivierjag2 Probably link to [Hacksore/bluelinky#96](https://github.com/Hacksore/bluelinky/issues/96)

I Try but only  23 work, I try  all other number but I cannot start the car.

**Comment by PierreLevres** [comment]
It is a know bug that Canadian temp is 1 degree off

**Comment by Hacksore** [comment]
This should be fixed now.
