### ISSUE TITLE
Unlock car doesn't function

### ISSUE THREAD

**Issue by PierreLevres** [SondreNjaastad/node-red-contrib-bluelinky#48]
Locking works, unlocking doesn't. Looking for the difference in de JS code I found a difference between the two functions. 

const car =  await client.getVehicle(this.bluelinkyConfig.vin) 
const result = await car.unlock();
should be
let car = await client.getVehicle(this.bluelinkyConfig.vin)
let result = await car.unlock();

After changing const to let in my local version, it works again.
Please confirm?

**Comment by holdestmade** [comment]
Lock and Unlock working ok for me, I have to leave a few minutes between lock/unlock commands though or I get a Duplicate Request error

**Comment by Hacksore** [comment]
`let` vs `const` are just JS semantics that wouldn't make a difference there. It's probably you trying to call the commands too quickly?

Further discuss this in discord, please.
