### ISSUE TITLE
"Cannot read property 'substring' of undefined"

### ISSUE THREAD

**Issue by olivierjag2** [SondreNjaastad/node-red-contrib-bluelinky#49]
I receive this new version When I run car status 

lock/unlock/start car works fine

"Cannot read property 'substring' of undefined"

**Comment by holdestmade** [comment]
The format seems to have changed. I had to remove vehicleSratus from the payload

**Comment by olivierjag2** [comment]
Do you modify the code?

**Comment by holdestmade** [comment]
No, I just adjusted my change nodes

**Comment by olivierjag2** [comment]
What I need to modify?

**Comment by holdestmade** [comment]
Assuming you do same as me with a change node:

Full status uses this:  payload.vehicleStatus.battery.batSoc

Status used to be the same but now needs to be payload.battery.batSoc

**Comment by olivierjag2** [comment]
you use full-carstatus?

**Comment by holdestmade** [comment]
I use both

**Comment by olivierjag2** [comment]
can you share your flow code?

**Comment by olivierjag2** [comment]
uselly I run this and I receive my objet, but I receive the same error message

2021-04-16 06:08:58node: ae55da4d.0f2c88
msg.payload : string[45]
"Cannot read property 'substring' of undefined"

<img width="679" alt="image" src="https://user-images.githubusercontent.com/31319364/115009515-5be70e80-9e7a-11eb-90ea-daa1a46eb854.png">

**Comment by holdestmade** [comment]
No that looks unrelated to what I mean. Maybe a login problem, see the Discord channel, there is discussion about it

**Comment by olivierjag2** [comment]
Yes last version

Do you have link for discord?

**Comment by holdestmade** [comment]
Click on Chat on this page (above Install)

https://github.com/Hacksore/bluelinky

**Comment by olivierjag2** [comment]
I try but I have always the same problem? can I return to .20?

**Comment by Hacksore** [comment]
Should be resolved in `0.0.22`
