### ISSUE TITLE
Update Node Help for car-odometer

### ISSUE THREAD

**Issue by justinoreilly** [SondreNjaastad/node-red-contrib-bluelinky#5]
The Node Help for car-odometer shows description for car-location.
<img width="319" alt="Screen Shot 2020-05-14 at 12 06 22 PM" src="https://user-images.githubusercontent.com/7625409/81958095-7a45e980-95db-11ea-8d57-212c82540d80.png">

**Comment by SondreNjaastad** [comment]
Fixed by @Hacksore , #6
