### ISSUE TITLE
Error:Constructor kia is not managed.

### ISSUE THREAD

**Issue by danielntamasi** [SondreNjaastad/node-red-contrib-bluelinky#52]
I face the following problem with the setup mentioned below. I tried to perform the "generic Kia account setup (although I'm not a 100% sure what that entails other than logging in and out from the app + resetting the password).
![image](https://user-images.githubusercontent.com/65130670/119275494-0e796200-bbdb-11eb-882a-741af0ca920b.jpeg)

**Comment by PierreLevres** [comment]
Kia USA is not supported yet. ..

**Comment by danielntamasi** [comment]
ohh. thanks, that wasn't obvious from the description & options that are choosable. 
is support for KIA USA on the roadmap?

Thank you for your answer in advance.

**Comment by PierreLevres** [comment]
There is not really a roadmap i believe, but there is a for sure wish ffor it, and it needs people that are able tot reverse engineer or log network traffic.

**Comment by Hacksore** [comment]
This can be tracked in the upstream lib via https://github.com/Hacksore/bluelinky/issues/135
