### ISSUE TITLE
EU Hyundai Kona - Cannot login

### ISSUE THREAD

**Issue by Flight777** [SondreNjaastad/node-red-contrib-bluelinky#56]
Happy new owner of the Kona Electric since this week so want to add it of course to my HA :)

However, I'm keep getting this error:

`@EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error Error: @EuropeanBrandAuthStrategy.login: Cannot find the argument userId in https://eu-account.hyundai.com/auth/realms/euhyundaiidm/login-actions/required-action?execution=kia-account-upgrade-email&client_id=97516a3c-2060-48b4-98cd-8e7dcd3c47b2&tab_id=NazxmMfIM5s.`

I don't have any previous Hyundai/Bluelink account, I tried logging in and out of the app and changing password but to no avail. Anyone knows what is going on?

Thanks!

**Comment by Flight777** [comment]
Thanks for checking @Hacksore

**Comment by PierreLevres** [comment]
What strikes me is that the message "?execution=kia-account-upgrade-email" contains a reference to KIA, while the URLs reference to Hyundai. In the code there is no mixup of the two brands. The part after " userId in" is generated by the hyundai server.
Apparently the hyundai server seems to think you have a kia Id?  Is it maybe possible you used that account on Kia servers before?

**Comment by Flight777** [comment]
> What strikes me is that the message "?execution=kia-account-upgrade-email" contains a reference to KIA, while the URLs reference to Hyundai. In the code there is no mixup of the two brands. The part after " userId in" is generated by the hyundai server. Apparently the hyundai server seems to think you have a kia Id? Is it maybe possible you used that account on Kia servers before?

Nope never owned a Kia in my life (so far ;)) and this is my first Hyundai.

**Comment by Flight777** [comment]
I think this is the same issue reported in a HASS add-on:

https://github.com/fuatakgun/kia_uvo/issues/56

Maybe it would help to work together on this?

**Comment by Hacksore** [comment]
Please someone raise a PR to fix, closing for now.
