### ISSUE TITLE
HTTP Response object missing after GetStatus etc

### ISSUE THREAD

**Issue by alan-down** [SondreNjaastad/node-red-contrib-bluelinky#59]
Hi,

I'm using the Get Status as part of an HTTP request/response to build a simple html page using a template.  It seems that the Get Status nodes don't preserve the HTTP res/req needed for this to work.  An error is produced from the response saying "No response object".

As a work-around I'm storing msg.res and msg.req in a flow variable and restoring them after the Get Status.

Is it possible to somehow preserve res & req?  My Node's too weak to contribute, sorry!

Alan

**Comment by Hacksore** [comment]
🤷‍♂️ but feel free to raise a new issue if needed
