### ISSUE TITLE
Update nodered library to bluelinky repo

### ISSUE THREAD

**Issue by binderth** [SondreNjaastad/node-red-contrib-bluelinky#61]
I noticed, this nodered library was updated in September and bluelinky repo got a release just last month. 
Are there plans to update this project regularly or is it possible to somehow link both, so that we get the bluelinky release updates automatically?

**Comment by Hacksore** [comment]
Fairly sure just uninstalling the addon and reinstalling will get the latest bluelinky

**Comment by HanschDennis** [comment]
True, I did an update yesterday, but I had to manually un + install the bluelinky module. It was not enough to only update "node-red-contrib-bluelinky".

**Comment by binderth** [comment]
I did:
`npm uninstall node-red-contrib-bluelinky`
`npm install node-red-contrib-bluelinky`
`sudo service nodered restart`

after that, the newest bluelinky was used.
