### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by nnoally** [SondreNjaastad/node-red-contrib-bluelinky#64]
Got an error when connecting to EU server (hyndai brand):
`error: @EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error Error: @EuropeanBrandAuthStrategy.login: Cannot find the argument userId in https://prd.eu-ccapi.hyundai.com:8080/web/v1/user/integration/auth`

Relates to : https://github.com/Hacksore/bluelinky/issues/199
Seems to be fixed with latest bluelinky version.

**Comment by HanschDennis** [comment]
Hi,
did you try to reinstall the bluelinky (not node-red-contrib-bluelinky!) node module (e.g. npm uninstall bluelinky)? My Hyundai is also in europe and it's working at the moment.

**Comment by Boxana** [comment]
Hi there,
"node-red-contrib-bluelinky" doesn't work for me anymore.
I can no longer log in (erro).
Already removed it from NOde Red and re-added it again with no success.
Can someone please help me?
It went well for weeks. I use version 0.27.

**Comment by HanschDennis** [comment]
@Boxana did remove the bluelinky module as well? I had to do it manually, it is not enough to only reinstall "node-red-contrib-bluelinky"

**Comment by Boxana** [comment]
Hi there,
it's working again.
Did it as written above with "npm uninstall bluelinky"
then reinstalled with "npm install bluelinky".
then removed "node-red-contrib-bluelinky" and set it up again.
finally restarted and now it works again.
I'm using an Openhabian as (how do you say that) patform.
When installing came the following.
"openhabian@openhab:~ $ sudo npm install bluelinky
npm WARN saveError ENOENT: no such file or directory, open '/home/openhabian/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/openhabian/package.json'
npm WARN openhabian No description
npm WARN openhabian No repository field.
npm WARN openhabian No README data
npm WARN openhabian No license field.

+ bluelinky@7.6.4
added 1 package from 1 contributor and audited 187 packages in 5,013s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
"
Unfortunately I don't know exactly what I'm doing there. Can someone please take a look?
Greeting
Christian

**Comment by PierreLevres** [comment]
> Hi there, it's working again. Did it as written above with "npm uninstall bluelinky" then reinstalled with "npm install bluelinky". ...... sudo npm install bluelinky.... Unfortunately I don't know exactly what I'm doing there. Can someone please take a look? Greeting Christian

What do you mean you don't know what you are doing?
I see you issuing an npm install, and issuing a sudo npm install 
Generally sudo-ing "npm install" is a bad idea, since it installs in a directory only alterable for the root user.

**Comment by hessijames79** [comment]
After having the same problem and reinstalling node-red-contrib-bluelinky witch updated bluelinky to 7.6.4 it worked again but failed after about 20 minutes. After some hours it worked again.

In 7.6.3 the stamp interval was set to 15 minutes, in 7.6.4 to 4 hours. Is there any simple way I can force node-red-contrib-bluelinky to use 7.6.3 again?

**Comment by PierreLevres** [comment]
Same here 12 minutes... and it starts to fail..

**Comment by Boxana** [comment]
it looks like the registration will drop out after 13 minutes. Then only a complete deploy or restart node red helps. After 4 hours it seems to work again automatically for 13 minutes.

**Comment by Boxana** [comment]
> After having the same problem and reinstalling node-red-contrib-bluelinky which updated bluelinky to 7.6.4 it worked again but failed after about 20 minutes. After some hours it worked again.
> 
> In 7.6.3 the stamp interval was set to 15 minutes, in 7.6.4 to 4 hours.

that matches mine. After about 12 minutes, the registration is canceled. restarting node red fixes it for about 12 minutes. Also a full deploy fixes it for about 12 min. if you wait 4 hours then it automatically goes back about 12 minutes without doing anything. do you already have a solution?

**Comment by HanschDennis** [comment]
@Boxana Did you try updating to bluelinky 7.6.5?

**Comment by PierreLevres** [comment]
> @Boxana Did you try updating to bluelinky 7.6.5?

I did, and indeed, seems fixed. Running well for two hours now ...

**Comment by nnoally** [comment]
> > @Boxana Did you try updating to bluelinky 7.6.5?
> 
> I did, and indeed, seems fixed. Running well for two hours now ...

Yes same for me.

**Comment by Boxana** [comment]
Thanks for this hint,
I've overlooked :-().
It looks like it's working now.
I have a completely different, unusual question.
Since I'm not familiar with github at all.
I am very grateful that there are people here who spend their free time with projects like this. I have set up a donation there and wonder if you can also increase the 1€.
I can't find an option to do that. I don't take it for granted that you get such support.
A hint would be nice.

**Comment by Helavi** [comment]
Hello, I really read all your comments carefully but still can't recognize what's the final solution is for the problem. What is meant with updating to  7.6.5? What do I have to do exactly? The version of node-red-contrib-bluelinky is 0.0.27, what's the other version 7.6.5 about?

**Comment by Boxana** [comment]
I uninstalled bluelinky in node red and then added it back.
then the installation will automatically get the current version. on Bluelinky.
I did it this way because the directory structure in Openhabian is different than an installation with a standalone node red.
everything is working again at the moment.

node-red-contrib-bluelinky has not changed but the program bllinky.
node-red-contrib-bluelinky accesses it.
I hope I explained that correctly 😅

**Comment by Helavi** [comment]
After node-red-restart it is not possible to get a connection, message below bluelinky nodes say since minutes: "Logging in....."

**Comment by Boxana** [comment]
I have the same problem since I wrote you how I did it.  Before that it ran about 3 hours.

**Comment by raleeSheffield** [comment]
I've had same issue for a few days now...

**Comment by Helavi** [comment]
Hi, mine is running for more than 1 day stable, don't know why, I've change nothing, but in's nice!

**Comment by Vitani** [comment]
How do you uninstall a node that is in-use? The pallete manager won't let me (I'm using Node-RED in Home Assistant, if that makes any difference)
![image](https://user-images.githubusercontent.com/5907401/154062590-b14c1d92-1756-4f1e-90f7-e8fa86d9823f.png)

**Comment by Vitani** [comment]
I had to restart Node-RED between removing & installing the node, but otherwise that worked perfectly, thank-you @PierreLevres !

**Comment by PierreLevres** [comment]
> I had to restart Node-RED between removing & installing the node, but otherwise that worked perfectly, thank-you @PierreLevres !

I updated the procedure, and submitted a PR for the readme

**Comment by binderth** [comment]
Since a few days I get an "error" for all my (previous functioning) flows:
![grafik](https://user-images.githubusercontent.com/9037329/155284406-9f49b4ec-6605-4d9c-a5c2-834db754f600.png)

You all are posting those logfiles - how can I reach them?

**Comment by Hacksore** [comment]
I have not following this issue much but if there is a continuing issue please raise a new one.
