### ISSUE TITLE
car death

### ISSUE THREAD

**Issue by Helavi** [SondreNjaastad/node-red-contrib-bluelinky#69]
Hello, I was so happy, that reading status information with the bluelinky node was working stable in the past time. I asked for SOC of HV battery every minute, this was obviously too much. Since this morning I cant't login into the Hyundai App any more, I get the message "The maximum number of daily vehible checks has been exceeded". But that's not all, my car is completely dead, it doesn't show any signs of life anymore, I even can't lock it. Does anybody has made a similar experience? Does anybody knows the maximum number of logins?

**Comment by PierreLevres** [comment]
Did you ask for status with refresh = true??? In that case you exhausted your 12V battery. You need a jumpstart....

**Comment by Helavi** [comment]
Yes, I did. And you are totally right, the 12V battery is empty. Thanks!
