### ISSUE TITLE
Please upgrade to 7.6.6

### ISSUE THREAD

**Issue by fromCologne** [SondreNjaastad/node-red-contrib-bluelinky#70]
Can you please upgrade this node with the base source 7.6.6 ?
I´ve problems with the stamp authentication in EU region and need the latest version to fix it.
Thank you very much.

**Comment by PierreLevres** [comment]
There is no need to push a new version of [node-red-contrib-bluelinky](https://github.com/SondreNjaastad/node-red-contrib-bluelinky#what-to-do-when-bluelinky-is-updated). In the readme there are instructions how to update the bluelinky files, see at node-red-contrib-bluelinky
