### ISSUE TITLE
Location information stopped working about a week ago

### ISSUE THREAD

**Issue by Jens5395** [SondreNjaastad/node-red-contrib-bluelinky#71]
About a week to ten days ago, the 'get location' node red procedure produces the following error:
payload: "error: TypeError: Cannot read properties of undefined (reading 'result')"
I have no idea how to get past this error message. Nothing was changed in my setup, it just started failing. 
Any idea what could be wrong? 
BTW, I am using 0.0.27 version of bluelinky and I am in Canada. The car is a Hiundai Kona EV

**Comment by Hacksore** [comment]
If this is still happening please raise a new issue.
