### ISSUE TITLE
Help Request on Input/Format for node "set-navigation"

### ISSUE THREAD

**Issue by stbuerger** [SondreNjaastad/node-red-contrib-bluelinky#74]
Not sure whether the node "set-navigation" is actually supported and functional, I'm very much interested in any documentation/Information/hints about the required payload input and format to use with it.

thx
-stefan

**Comment by PierreLevres** [comment]
Yes, it is supported (in the EU).
In my node-red flows, I generate a route (using a ABRP api-call) either from home or from my current location to a destination (given the current SoC and the type of car).
The output from the ABRP is then rewritten to a format usable by the car and send to the car.

The payload for the node should be an array of EUPOIInformation objects. It takes a maximum of three points, in reverse order, so the final destination comes first in the array.
The format for the EUPOIInformation is documented in de bluelinky code https://github.com/Hacksore/bluelinky/blob/master/src/interfaces/european.interfaces.ts <https://github.com/Hacksore/bluelinky/blob/master/src/interfaces/european.interfaces.ts>.

Example plotting a route for an e-Niro 64 from Paris to Berlin with 90% SoC:
[{"phone":"","zip":"","lang":1,"src":"HERE","placeid":"","addr":"Berlin, Germany","coord":{"alt":0,"type":0,"lat":52.51705655410405,"lon":13.38890075683594},"waypointID":0,"name":"Berlin, Germany"},{"phone":"","zip":"","lang":1,"src":"HERE","placeid":"","addr":"","coord":{"alt":0,"type":0,"lat":50.655355,"lon":5.710963},"waypointID":1,"name":"Tignee [Ionity]"},{"phone":"","zip":"","lang":1,"src":"HERE","placeid":"","addr":"","coord":{"alt":0,"type":0,"lat":50.336704,"lon":3.455931},"waypointID":2,"name":"Valenciennes Supercharger [Tesla]"}]

Example plotting a route for an e-Niro 64 from Rotterdam to Amsterdam with 90% SoC:
[{"phone":"","zip":"","lang":1,"src":"HERE","placeid":"","addr":"Amsterdam, Netherlands","coord":{"alt":0,"type":0,"lat":52.3727598,"lon":4.8936041},"waypointID":0,"name":"Amsterdam, Netherlands”}]

**Comment by stbuerger** [comment]
THX a lot for the detailed explanation.
I just successfully tested it with a Kia Sorrento (MQ4, Build 2020 , Germany, AWD, Diesel, 148kW) .
