### ISSUE TITLE
Worked once...

### ISSUE THREAD

**Issue by wabiloo** [SondreNjaastad/node-red-contrib-bluelinky#76]
I've installed the module on my node-red server, and created a very basic workflow, just to get an impression of the payload coming back when requesting car status:

<img width="779" alt="Screenshot 2022-09-19 at 13 22 01" src="https://user-images.githubusercontent.com/4056263/191016360-b6b342b8-9dee-43ea-9c7e-18790ff14498.png">

It has worked exactly once. Since then, absolutely nothing. The icon shows "Ready" but nothing happens. Nothing is sent to debug. 

I restarted node-red on my raspberryPi, and then tested again. And it worked. Twice...  and then never again. Same after each restart of the service...

Any idea?  Is there any system log I could look at to try and understand what's going on?

**Comment by PierreLevres** [comment]
'Ready' merely means that a valid connection with the underlying bluelinky is active.
Tips: 
1. You might want to try the 'login' node  when the node doest not return anything. If it works well after a login or restart of node red, problem could be in the stamps used.
2. You might want to try the 'car-fullstatus' node
3. You can debug with only the bluelinky ts code thus pinpointing the problem to bluelinky or node-red

Could you check the versions of node-red-contrib-bluelinky and bluelinky in your node-red/node_modules folders.
Latest should be: 
node-red-contrib-bluelinky = 0.0.28
bluelinky = 7.6.6 

What are your versions? What car brand, car type and region ? Does your app work fine with the same credentials?

**Comment by Hacksore** [comment]
You can enable `LOG_LEVEL=debug` in your node-red settings.js file to help debug this more.

https://github.com/hassio-addons/addon-node-red/issues/879
https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#time-zone-configuration

**Comment by wabiloo** [comment]
I've not really done anything, but it seems to be working now. I've set the frequency of polling to 30 minutes. 
Is there maybe something in the bluelinky code that "protects" against flooding? (although my initial tests were still minutes apart)

**Comment by Hacksore** [comment]
Probably related to rate limiting, gonna close this for now.
