### ISSUE TITLE
Update to latest bluelinky Release

### ISSUE THREAD

**Issue by Sauwald** [SondreNjaastad/node-red-contrib-bluelinky#8]
Please update to 5.1.1
Thank you.

**Comment by joepv** [comment]
Yes, I want that to, because my Kona 2020 is not working, and with bluelinky version `5.1.1` it is :)

**Comment by jawgardner** [comment]
Yes please do this. My Sonata 2020 Hybrid works once, then after that I get authentication errors.

**Comment by SondreNjaastad** [comment]
Sorry for the sudden inactiveness, i've become a father, so been quite busy :) I will sit down and see if i can push what i was doing last time now :)

**Comment by SondreNjaastad** [comment]
npm package updated. Bluelinky is now v5.2.0, and i've also added status on all nodes.
