### ISSUE TITLE
Can not log in Europe

### ISSUE THREAD

**Issue by FSHelgeland** [SondreNjaastad/node-red-contrib-bluelinky#83]
It stopped working this morning. So this morning I have done a update to NodeRed V 3.02 running on a rpi, and I have tried both an update and a reinstall of the bluelinky node, exporting importing nodes. Still can not log in. However it is possible to log in if I switch to Canada, but then again nothing works of course. 

Any tips how to get it up running again?
Best regards
Freddy

**Comment by Michaelnorge** [comment]
We using ioBroker and bluelink-adapter and have since a couple of days problems as well.
Probably bluelink is doing some changes ....
https://forum.iobroker.net/topic/43592/adapter-hyundai-bluelink-oder-kia-uvo

**Comment by FSHelgeland** [comment]
Finally get it to log in again. Been reading through the old issues in here as well. 

I have updated my node red to latest version 3.02
Did a apt update && apt full-upgrade
Exported my nodes to a file
Removed node-red-contrib-bluelinky
Did a node-red-restart
installed node-red-contrib-bluelinky again
and finally I imorted my nodes again and did a deploy. 
Seems that did the trick.

**Comment by FSHelgeland** [comment]
Same problem again now, I will try to follow my last recipe.

**Comment by PierreLevres** [comment]
I’m also heaving trouble loggin in through node-red and bluelinky from home-assistant. Discord channel mentions it.

**Comment by FSHelgeland** [comment]
Tried the recipe from last time, but now luck this time. Can not log in, I am active on the discord channel as well.

**Comment by Hacksore** [comment]
I have not following this issue much but if there is a continuing issue please raise a new one.
