### ISSUE TITLE
"Invalid request body - Invalid deviceID"

### ISSUE THREAD

**Issue by jntz** [SondreNjaastad/node-red-contrib-bluelinky#84]
Hey, 

since a few days this beautiful script stopped working with html msg "Invalid request body - Invalid deviceID".

Seems it has to do with changes KIA did within their API, as they also forced users to change their mobile app. 

Version: 0.0.30
Location: EU
Car Manufacturer: KIA

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/348

You are doing a great job! Thanks a lot, i owe you a beer!

J

**Comment by Hacksore** [comment]
Moving target with their API my guess, if persists please raise upstream.
https://github.com/Hacksore/bluelinky
