### ISSUE TITLE
"Invalid request body - Invalid deviceId" after "Lock car" - Workaround: re-login

### ISSUE THREAD

**Issue by solaech** [SondreNjaastad/node-red-contrib-bluelinky#85]
Hello,
when i lock my car with the "Lock car" function it does work.
But after the Lock-Function i'm unable to request the car-status again with "Get status".

I get this Error Message:
`"ManagedBluelinkyError: @EuropeVehicle.status: [400] Bad Request on [GET] https://prd.eu-ccapi.kia.com:8080/api/v2/spa/vehicles/ab22171a-...-ef1aee04bc04/status - {"retCode":"F","resCode":"4002","resMsg":"Invalid request body - Invalid deviceId. ","msgId":"ef918e89-7888-4b70-8f39-ebe5fce8d4fd"}"`

My workaround is to add the "Login" function after the "Lock car" function with a delay of 10 Seconds.
If i do that i'm successfully able to request the Status with "Get status" again.

node-red-contrib-bluelinky 0.0.30
bluelinky 8.1.1
Location: EU
Vehicle: KIA Sportage

**Comment by PierreLevres** [comment]
thank you. It seems to happen when notifications are send by the car. Also after charging. Something happened to the notification system which invalidates a device when a notification can’t be received.
________________________________
Van: solaech ***@***.***>
Verzonden: Friday, July 7, 2023 11:54:51 PM
Aan: SondreNjaastad/node-red-contrib-bluelinky ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [SondreNjaastad/node-red-contrib-bluelinky] "Invalid request body - Invalid deviceId" after "Lock car" (Issue #85)


Hello,
when i lock my car with the "Lock car" function it does work.
But after the Lock-Function i'm unable to request the car-Status again with "Get status".
I get this Error Message:
"ManagedBluelinkyError: @EuropeVehicle.status: [400] Bad Request on [GET] https://prd.eu-ccapi.kia.com:8080/api/v2/spa/vehicles/ab22171a-cc51-4d7b-9b68-ef1aee04bc04/status - {"retCode":"F","resCode":"4002","resMsg":"Invalid request body - Invalid deviceId. ","msgId":"ef918e89-7888-4b70-8f39-ebe5fce8d4fd"}"
My workaround is to add the "Login" function after the "Lock car" function with a delay of 10 Seconds.
If i do that i'm successfully able to request the Status with "Get status" again.

**Comment by Hacksore** [comment]
Maybe a service issue, closing for now but open a new issue if needed.
