### ISSUE TITLE
Bluelinky nodes seem to create new message objects, discarding metadata

### ISSUE THREAD

**Issue by olithissen** [SondreNjaastad/node-red-contrib-bluelinky#89]
First of all: Thank you for bridging Bluelinky to Node-RED!

### Problem

Bluelinky nodes seem to create new messages on output instead of extending the original input data. 

I just noticed this when I tried to forward output to PostgreSQL: My input-message provides an `msg.topic` property with the name of the used endpoint (like `DriveHistory`). The output message of `DriveHistory` only contains the payload object and a new `_msgid`. So I have no way to pass additional information through the node.

### Possible fix

A fix might be quite easy: Not sending an anonymous object in `node.send()` but by manipulating and sending the original `msg` instead. (This would need to be done for all nodes and goes for the error responses as well)

```javascript
        // before
        // ...
        node.send({
          payload: result,
        });
        // ...

        // after
        // ...
        msg.payload = result;
        node.send(msg);
        // ...
```

Let me know what you think!

All the best!
Oli

**Comment by Hacksore** [comment]
Seems reasonable @olithissen, care to make a PR and I'll take a look?

**Comment by olithissen** [comment]
As mentioned above, this is not my day to day ecosystem and I failed at step one.

I went the straight forward way, installed Node-RED locally and installed the cloned repo via `npm install ~/dev/node-red-contrib-bluelinky`. All the nodes are available but after configuring and deploying in Node-RED I just get a _BlueLinky is not a constructor_ error. This is even before I do any code changes. 

- Ubuntu 24.04 LTS
- Node-RED 3.1.10
- Tested with various Node LTS versions (from 16 to 20)

Decades of Java did not prepare me for this. Any hints?

**Comment by Hacksore** [comment]
Hmm I thought it was fixed in https://github.com/SondreNjaastad/node-red-contrib-bluelinky/pull/87

Can you make sure you have the latest node red addon installed?
<img width="1281" alt="image" src="https://github.com/SondreNjaastad/node-red-contrib-bluelinky/assets/996134/1227db28-0f47-42c4-8971-f82b788c271d">

**Comment by olithissen** [comment]
I think I'm missing something: Installing via Node-RED palette works as well as `npm install node-red-contrib-bluelinky` from within my Node-RED directory. However doing the same with the locally cloned repo `npm install ~/dev/node-red-contrib-bluelinky` installs only node-red-contrib-bluelinky but none of the ~135 required dependencies.

**Comment by Hacksore** [comment]
@olithissen my knowledge of node-red is limited so if you figure it out please do share more.

**Comment by Cadkey** [comment]
I found the problem. In Docker, images no longer used must have disrupted the container. Sorry for the local problem on my device.
